### ISSUE TITLE
Typo in line 136 of x86.pl, no?

### ISSUE THREAD

**Issue by a0-prw** [MahdiSafsafi/opcodesDB#2]
ymm => { type => 'ymmreg', size => 256, names => [ map 'zmm' . $_, 0 .. 31 ] },

'zmm' should be 'ymm'

ymm => { type => 'ymmreg', size => 256, names => [ map 'ymm' . $_, 0 .. 31 ] },

**Comment by MahdiSafsafi** [comment]
Yes you're right. I just fixed it.

**Comment by a0-prw** [comment]
Thank you :)

-------- Original message --------
